import type { ComposedEmail, Opportunity } from "@/lib/outbound/types";

/**
 * Post-generation quality gate.
 *
 * A prompt is a request, not a guarantee. Every generated email is checked here
 * before it is allowed anywhere near the send queue, and a failure sends the
 * composer round again with the specific violations named. This is the
 * difference between "usually not templated" and "never sends the phrase 'I
 * hope this email finds you well'".
 */

/** Phrases that mark an email as mass-produced. Matched case-insensitively. */
export const BANNED_PHRASES = [
  "i hope you're doing well",
  "i hope you are doing well",
  "hope you're well",
  "hope this email finds you",
  "hope this finds you well",
  "i hope this message finds you",
  "just checking in",
  "just following up",
  "just wanted to reach out",
  "just reaching out",
  "quick question",
  "circling back",
  "bumping this",
  "touching base",
  "we help businesses",
  "we help companies",
  "we specialise in helping",
  "we specialize in helping",
  "i wanted to reach out",
  "in today's fast-paced",
  "in today's digital",
  "game-changer",
  "game changer",
  "leverage our",
  "cutting-edge",
  "state-of-the-art",
  "revolutionise your",
  "revolutionize your",
  "take your business to the next level",
  "unlock the power",
  "supercharge your",
  "at the end of the day",
  "let me know if you have any questions",
  "looking forward to hearing from you",
  "i came across your website and",
  "i stumbled upon your",
  "as a fellow",
  "did you see my last email",
  "per my last email",
  "as an ai",
  "i'm an ai",
  "delve into",
  "in the realm of",
  "it's worth noting that",
  "seamlessly integrate",
  "robust solution",
  "synergy",
  "low-hanging fruit",
  "move the needle",
  "boost your roi",
  "drive growth",
  "dear sir or madam",
  "to whom it may concern",
];

const MIN_WORDS = 70;
const MAX_WORDS = 140;
const MIN_SUBJECT_WORDS = 2;
const MAX_SUBJECT_WORDS = 9;

export type GuardrailViolation = {
  code:
    | "banned_phrase"
    | "too_short"
    | "too_long"
    | "no_subject"
    | "subject_length"
    | "subject_shouting"
    | "markdown"
    | "emoji"
    | "placeholder"
    | "unsupported_claim"
    | "too_similar"
    | "meta_reference";
  detail: string;
};

export type GuardrailResult = {
  ok: boolean;
  violations: GuardrailViolation[];
  wordCount: number;
};

export function checkEmail(
  email: ComposedEmail,
  ctx: {
    opportunities: Opportunity[];
    /** Bodies of recent emails to other leads — catches convergence. */
    recentBodies?: string[];
    company: string;
    contactName?: string | null;
  }
): GuardrailResult {
  const v: GuardrailViolation[] = [];
  const body = email.body ?? "";
  const subject = email.subject ?? "";
  const lower = body.toLowerCase();
  const wordCount = countWords(body);

  for (const phrase of BANNED_PHRASES) {
    if (lower.includes(phrase)) {
      v.push({ code: "banned_phrase", detail: `contains "${phrase}"` });
    }
  }

  if (wordCount < MIN_WORDS) {
    v.push({ code: "too_short", detail: `${wordCount} words, minimum is ${MIN_WORDS}` });
  } else if (wordCount > MAX_WORDS) {
    v.push({ code: "too_long", detail: `${wordCount} words, maximum is ${MAX_WORDS}` });
  }

  if (!subject.trim()) {
    v.push({ code: "no_subject", detail: "no subject line produced" });
  } else {
    const sw = countWords(subject);
    if (sw < MIN_SUBJECT_WORDS || sw > MAX_SUBJECT_WORDS) {
      v.push({
        code: "subject_length",
        detail: `subject is ${sw} words, should be ${MIN_SUBJECT_WORDS}-${MAX_SUBJECT_WORDS}`,
      });
    }
    if (subject === subject.toUpperCase() && /[A-Z]{4}/.test(subject)) {
      v.push({ code: "subject_shouting", detail: "subject is in capitals" });
    }
    if (/[!]{1,}/.test(subject)) {
      v.push({ code: "subject_shouting", detail: "subject contains an exclamation mark" });
    }
  }

  // Markdown in a plain-text cold email is a dead giveaway.
  if (/(\*\*|^\s*[-*+]\s|^#{1,6}\s|\[[^\]]+\]\([^)]+\))/m.test(body)) {
    v.push({ code: "markdown", detail: "body contains markdown formatting" });
  }

  if (EMOJI.test(body) || EMOJI.test(subject)) {
    v.push({ code: "emoji", detail: "contains an emoji" });
  }

  // Unfilled template slots. These have shipped before in other tools; never again.
  const placeholder = body.match(/\[[A-Za-z _]{2,30}\]|\{\{[^}]+\}\}|<[A-Za-z _]{2,30}>|\bXYZ\b/);
  if (placeholder) {
    v.push({ code: "placeholder", detail: `unfilled placeholder ${placeholder[0]}` });
  }

  if (/\b(as an ai|language model|i am an ai|generated by)\b/i.test(body)) {
    v.push({ code: "meta_reference", detail: "email refers to itself as AI-generated" });
  }

  // Fabrication check: numbers that appear nowhere in the evidence we hold.
  const evidence = [
    ...ctx.opportunities.map((o) => `${o.title} ${o.evidence}`),
    ctx.company,
    ctx.contactName ?? "",
  ]
    .join(" ")
    .toLowerCase();
  for (const claim of extractHardClaims(body)) {
    if (!evidence.includes(claim.toLowerCase())) {
      v.push({
        code: "unsupported_claim",
        detail: `states "${claim}" which is not in the site evidence`,
      });
    }
  }

  for (const prev of ctx.recentBodies ?? []) {
    const sim = similarity(body, prev);
    if (sim > 0.6) {
      v.push({
        code: "too_similar",
        detail: `${Math.round(sim * 100)}% similar to a recently generated email`,
      });
      break;
    }
  }

  return { ok: v.length === 0, violations: v, wordCount };
}

/** Turn violations into an instruction the composer can act on. */
export function violationsToInstruction(violations: GuardrailViolation[]): string {
  return [
    "Your previous draft was rejected. Fix every point below and rewrite it completely — do not patch the old version.",
    ...violations.map((x) => `- ${x.detail}`),
    "Keep the same skeleton (greeting, opening, structure, tone, CTA, sign-off) you were given.",
  ].join("\n");
}

// ─── helpers ──────────────────────────────────────────────

const EMOJI =
  /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}\u{1F900}-\u{1F9FF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}]/u;

function countWords(s: string): number {
  return s.trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Claims a reader would treat as researched fact — percentages, money, counts
 * of things, durations. If the model produced one that is not in the evidence
 * we gave it, it made it up.
 */
function extractHardClaims(body: string): string[] {
  const out: string[] = [];
  const patterns = [
    /\b\d{1,3}%/g,
    /[£$€]\s?\d[\d,.]*\s?(k|m|bn)?\b/gi,
    /\b\d[\d,]{2,}\s+(customers|clients|users|bookings|leads|enquiries|orders|reviews|hours)\b/gi,
    /\b\d+\s+(years|months)\s+(in business|of trading|running)\b/gi,
  ];
  for (const re of patterns) {
    for (const m of body.matchAll(re)) out.push(m[0].trim());
  }
  return [...new Set(out)];
}

/**
 * Jaccard similarity over 3-word shingles. Cheap, and it catches the real
 * failure mode — two emails with the same sentence scaffolding and swapped
 * nouns — which a plain word-overlap check misses.
 */
function similarity(a: string, b: string): number {
  const sa = shingles(a);
  const sb = shingles(b);
  if (!sa.size || !sb.size) return 0;
  let inter = 0;
  for (const s of sa) if (sb.has(s)) inter++;
  return inter / (sa.size + sb.size - inter);
}

function shingles(s: string): Set<string> {
  const words = s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean);
  const out = new Set<string>();
  for (let i = 0; i + 2 < words.length; i++) {
    out.add(`${words[i]} ${words[i + 1]} ${words[i + 2]}`);
  }
  return out;
}
